# Generated by Django 4.1.2 on 2022-12-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id_produtos', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('kit_relacao', models.CharField(max_length=100)),
                ('pneu', models.CharField(max_length=100)),
                ('retrovisor', models.CharField(max_length=100)),
                ('painel', models.CharField(max_length=100)),
                ('oleo', models.CharField(max_length=100)),
            ],
        ),
    ]
