# Generated by Django 4.1.2 on 2022-12-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fornecedores',
            fields=[
                ('id_fornecedores', models.AutoField(primary_key=True, serialize=False)),
                ('pecas', models.CharField(max_length=100)),
                ('pneus', models.CharField(max_length=100)),
                ('oleo', models.CharField(max_length=100)),
                ('capacetes', models.CharField(max_length=100)),
                ('capa_chuva', models.CharField(max_length=100)),
            ],
        ),
    ]
