# Generated by Django 4.1.2 on 2022-12-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('id_vendas', models.AutoField(primary_key=True, serialize=False)),
                ('clientes', models.CharField(max_length=100)),
                ('produtos', models.CharField(max_length=100)),
                ('compra', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=11)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
