# Generated by Django 4.1.2 on 2022-12-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notafiscal',
            fields=[
                ('id_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
