# Generated by Django 4.1.2 on 2022-12-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notafiscal',
            old_name='id_Cliente',
            new_name='id_notafiscal',
        ),
    ]
